config/routes.rb
WomenOfWaze::Application.routes.draw do

  match "/admin" => "admin#index"

 
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  
  devise_scope :user do
    get "users/login"  => "devise/sessions#new"
    get "users/logout" => "devise/sessions#destroy"
  end
  resources :products do
    collection do
      get 'catalogue'
    end
    member do
      get 'detail'
    end
  end

  resources :sub_categories
  resources :categories 
  resources :enquiries
 

  match "/aboutus" => "home#aboutus"
  root :to => 'home#index'
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :products ,:order => 'price DESC'

  validates :name, :presence => { :message => "is required" },
            :uniqueness => { :message => "should be unique" },
            :length => { :maximum => 64, :message => "should not be more than 64 characters" }
  validates :description, :presence => { :message => "is required" },
            :length => { :maximum => 64, :message => "should not be more than 64 characters" }
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  # GET /sub_categories
  # GET /sub_categories.xml
  def index
    @category = Category.find_by_id(params[:category_id]) if params[:category_id]
    @sub_categories = @category.sub_categories if @category
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sub_categories }
    end
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.xml
  def show
    #    @category = Category.find(params[:id])
    @sub_category = SubCategory.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sub_category }
    end
  end

  # GET /sub_categories/new
  # GET /sub_categories/new.xml
  def new
    @category = Category.find_by_id(params[:category_id]) if params[:category_id]
    @sub_category = SubCategory.new(:category_id => params[:category_id]) if @category
   
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sub_category }
    end
  end

  # GET /sub_categories/1/edit
  def edit
    @sub_category = SubCategory.find(params[:id])
  end

  # POST /sub_categories
  # POST /sub_categories.xml
  def create
    @category = Category.find_by_id(params[:category_id]) if params[:category_id]
    @sub_category = SubCategory.new(params[:sub_category].merge(:category_id => params[:category_id])) if @category
   
    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to(@sub_category, :notice => 'Sub category was successfully created.') }
        format.xml  { render :xml => @sub_category, :status => :created, :location => @sub_category }
      else
        format.html { render :action => 'new' }
        format.xml  { render :xml => @sub_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sub_categories/1
  # PUT /sub_categories/1.xml
  def update
    @sub_category = SubCategory.find(params[:id])

    respond_to do |format|
      if @sub_category.update_attributes(params[:sub_category])
        format.html { redirect_to(@sub_category, :notice => 'Sub category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sub_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.xml
  def destroy
    @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy

    respond_to do |format|
      format.html { redirect_to sub_categories_path(:category_id => @sub_category.category_id) }
      format.xml  { head :ok }
    end
  end

 end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <link rel="stylesheet" href="../stylesheets/admin_style.css"/>
    <%= javascript_include_tag "jquery.validate.min.js", "admin_custom.js" %>
  </head>
  <body>
    <div class="wrapper container_24">
      <div class="logout_layout"><%= render :partial => 'shared/logout' %></div>
      <header class="banner">
        <span>An initiative of <a id="tcs_link" href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the women of waze.</span>
      </header>
      <section class="admincontent">
        <div class="admin-banner">
          Welcome Admin
        </div>
        <div class="admin-center">
          <div class="admin-option">
            <%= form_for(@sub_category, :html => { :id => "submit_form" }) do |f| %>
              <% if @sub_category.errors.any? %>
                <div id="error_explanation" class ="field_with_errors">
                  <h2><%= pluralize(@sub_category.errors.count, "error") %> prohibited this category from being saved:</h2>
                  <ul>
                    <% @sub_category.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <table>
                <tr>
                  <td><%= f.label :name %></td>
                  <td><%= f.text_field :name%></td>
                </tr>
                <tr>
                  <td><%= f.label :description %></td>
                  <td><%= f.text_area :description%></td>
                </tr>
                <% if @category %>
                  <%= hidden_field_tag :category_id, @category.id %>
                <%end%>
                <tr>
                  <td><%= link_to 'Back', sub_categories_path(:category_id => @sub_category.category_id ) %></td>
                  <td><%= f.submit %></td>
                </tr>
              </table>
            <% end %>
          </div>
        </div>
      </section>
    </div>
  </body>
</html>

app/views/sub_categories/edit.html.erb
<%= render 'form' %>
<%= javascript_tag "displayAction('Edit Sub-Category')" %>

app/views/sub_categories/index.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <link rel="stylesheet" href="../stylesheets/admin_style.css"/>
  </head>
  <body>
    <div class="wrapper container_24">
      <div class="logout_layout"><%= render :partial => 'shared/logout' %></div>
      <header class="banner">
        <span>An initiative of <a id="tcs_link" href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the women of waze.</span>
      </header>
      <section class="admincontent">
        <div class="admin-banner">
          Welcome Admin
        </div>
        <div class="admin-page-header">Sub-Categories for '<%=@category.name.capitalize%>' Category</div><br/><br/>
        <div class="admin-option">
          <%= link_to 'Add New SubCategory', new_sub_category_path(:category_id => @category.id) %>&nbsp;&nbsp;
          <%= link_to 'Back to Categories', categories_path %>&nbsp;&nbsp;
          <%= link_to 'Back to Admin Home', admin_path %>
        </div>

        <div class="categories-table">
          <table>
            <thead>
              <tr>
                <% if @sub_categories.empty?  %>
              <b>No Sub-Category for '<%=@category.name.capitalize%>' Category</b>
            <%else%>
              <th>Sub-Category Name</th><th>Description</th><th>Edit</th><th>Delete</th><th>Manage Associated Products</th>
            <%end%>
            </tr>
            </thead>
            <tbody>
              <% @sub_categories.each do |sub_category| %>
                <tr>
                  <td class="p-category"><%= link_to sub_category.name ,sub_category %></td>
                  <td><%= sub_category.description %></td>
                  <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
                  <% if sub_category.products.empty? %>
                    <td><%= link_to 'Delete', sub_category, :confirm => 'Are you sure?', :method => :delete  %></td>
                  <%else%>
                    <td><a class="admin-undelete" title="You cannot delete this sub category until you delete all the products associated with it.">Delete</a></td>
                  <%end%>
                  <td><%= link_to 'Manage Products', products_path(:sub_category_id => sub_category.id) %></td>
                </tr>
              <%end%>

            </tbody>
          </table>
        </div>

      </section>
    </div>
  </body>
</html>

app/views/sub_categories/new.html.erb
<%= render 'form' %>
<%= javascript_tag "displayAction('Add New Sub-Category')" %>

app/views/sub_categories/show.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
   <link rel="stylesheet" href="../stylesheets/admin_style.css"/>
   <%= javascript_include_tag "jquery.validate.min.js", "admin_custom.js" %>
  </head>
  <body>
    <div class="wrapper container_24">
      <div class="logout_layout"><%= render :partial => 'shared/logout' %></div>
      <header class="banner">
        <span>An initiative of <a id="tcs_link" href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the women of waze.</span>
      </header>
      <section class="bodycontent">
        <div class="admin-banner">
          Welcome Admin
        </div>
        <div class="admin-page-header">'<%=@sub_category.name.capitalize%>' Sub-Category</div>
        <div class="admin-center">
          <div class="admin-option">
            <table>
              <p id="notice"><%= notice %></p>

              <p>
                <b>Name:</b>
                <%= @sub_category.name %>
              </p>

              <p>
                <b>Description:</b>
                <%= @sub_category.description %>
              </p>
              <tr>
                <td><%= link_to 'Edit', edit_sub_category_path(@sub_category) %></td>
                <td><%= link_to 'Back', sub_categories_path(:category_id => @sub_category.category_id ) %></td>
              </tr>
            </table>
          </div>
        </div>
      </section>
    </div>
  </body>
</html>