config/routes.rb
WomenOfWaze::Application.routes.draw do

  match "/admin" => "admin#index"

 
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  
  devise_scope :user do
    get "users/login"  => "devise/sessions#new"
    get "users/logout" => "devise/sessions#destroy"
  end
  resources :products do
    collection do
      get 'catalogue'
    end
    member do
      get 'detail'
    end
  end

  resources :sub_categories
  resources :categories 
  resources :enquiries
 

  match "/aboutus" => "home#aboutus"
  root :to => 'home#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories,:order => 'name ASC'

  validates :name, :presence => { :message => "is required" } ,
            :uniqueness => { :message => "should be unique" },
            :length => { :maximum => 64, :message => "should not be more than 64 characters" }
  validates :description, :presence => { :message => "is required" },
            :length => { :maximum => 64, :message => "should not be more than 64 characters" }


  def self.catalogue_details
    self.includes({:sub_categories => :products})
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
   <link rel="stylesheet" href="../stylesheets/admin_style.css"/>
   <%= javascript_include_tag "jquery.validate.min.js", "admin_custom.js" %>
  </head>
  <body>
    <div class="wrapper container_24">
      <div class="logout_layout"><%= render :partial => 'shared/logout' %></div>
      <header class="banner">
        <span>An initiative of <a id="tcs_link" href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the women of waze.</span>
      </header>
      <section class="admincontent">
        <div class="admin-banner">
          Welcome Admin
        </div>
         <div class="admin-center">
          <div class="admin-option">
            <%= form_for(@category, :html => { :id => "submit_form" }) do |f| %>
              <% if @category.errors.any? %>
                <div id="error_explanation" class ="field_with_errors">
                  <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
                  <ul>
                    <% @category.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <table>
                <tr>
                  <td><%= f.label :name %></td>
                  <td><%= f.text_field :name %></td>
                </tr>
                <tr>
                  <td><%= f.label :description %></td>
                  <td><%= f.text_area :description %></td>
                </tr>
                <tr>
                <td><%= link_to 'Back', categories_path %></td>
                <td><%= f.submit %></td>
                </tr>
              </table>
            <% end %>
          </div>
        </div>
      </section>
    </div>
  </body>
</html>

app/views/categories/edit.html.erb
<%= render 'form' %>
<%= javascript_tag "displayAction('Edit Category')" %>

app/views/categories/index.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
   <link rel="stylesheet" href="../stylesheets/admin_style.css"/>
   <%= javascript_include_tag "jquery.validate.min.js", "admin_custom.js" %>
  </head>
  <body>
    <div class="wrapper container_24">
      <div class="logout_layout"><%= render :partial => 'shared/logout' %></div>
      <header class="banner">
        <span>An initiative of <a id="tcs_link" href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the women of waze.</span>
      </header>
      <section class="admincontent">
        <div class="admin-banner">
          Welcome Admin
        </div>
        <div class="admin-page-header">Categories Page</div><br/><br/>
        <div class="admin-option"><%= link_to 'Add New Category', new_category_path %>&nbsp;&nbsp;
        <%= link_to 'Back to Admin Home', admin_path %>
        </div>
        <div class="categories-table">
          <table>
            <thead>
              <tr>
                <% if @categories.empty? %>
              <b>No Categories</b>
            <%else%>
              <th>Category Name</th><th>Description</th><th>Edit</th><th>Delete</th><th>Manage Associated SubCategories</th>
            <%end%>
            </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td class="p-category"><%= link_to category.name, category %></td>
                  <td><%= category.description %></td>
                  <td><%= link_to 'Edit', edit_category_path(category) %></td>
                  <%if category.sub_categories.empty? %>
                    <td><%= link_to 'Delete', category, :confirm => 'Are you sure?', :method => :delete %></td>
                  <%else%>
                    <td><a class="admin-undelete" title="You cannot delete this category until you delete all the sub-categories associated with it.">Delete</a></td>
                  <%end%>
                  <td><%= link_to 'Manage SubCategories', sub_categories_path(:category_id => category.id) %></td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </body>
</html>

app/views/categories/new.html.erb
<%= render 'form' %>
<%= javascript_tag "displayAction('Add New Category')" %>

app/views/categories/show.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <link rel="stylesheet" href="../stylesheets/admin_style.css"/>
    <%= javascript_include_tag "jquery.validate.min.js", "admin_custom.js" %>
  </head>
  <body>
    <div class="wrapper container_24">
      <div class="logout_layout"><%= render :partial => 'shared/logout' %></div>
      <header class="banner">
        <span>An initiative of <a id="tcs_link" href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the women of waze.</span>
      </header>
      <section class="bodycontent">
        <div class="admin-banner">
          Welcome Admin
        </div>
        <div class="admin-page-header">'<%=@category.name.capitalize%>' Category</div>
        <div class="admin-center">
          <div class="admin-option">
            <table>
              <p id="notice"><%= notice %></p>

              <p>
                <b>Name:</b>
                <%= @category.name %>
              </p>

              <p>
                <b>Description:</b>
                <%= @category.description %>
              </p>
              <tr>
                <td><%= link_to 'Edit', edit_category_path(@category) %></td>
                <td><%= link_to 'Back', categories_path %></td>
              </tr>
            </table>
          </div>
        </div>
      </section>
    </div>
  </body>
</html>