config/routes.rb
WomenOfWaze::Application.routes.draw do

  match "/admin" => "admin#index"

 
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  
  devise_scope :user do
    get "users/login"  => "devise/sessions#new"
    get "users/logout" => "devise/sessions#destroy"
  end
  resources :products do
    collection do
      get 'catalogue'
    end
    member do
      get 'detail'
    end
  end

  resources :sub_categories
  resources :categories 
  resources :enquiries
 

  match "/aboutus" => "home#aboutus"
  root :to => 'home#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  include Mixins::PaperclipStorageDecider

 
  belongs_to :sub_category

  has_attached_file :photo, @paperclip_storage
    
    
  validates :name, :presence => {:message => "is required"},
            :uniqueness => {:message => "should be unique"},
            :length => {:maximum => 64, :message => "should not be more than 64 characters"}
  validates :description, :presence => {:message => "is required"},
            :length => {:maximum => 256, :message => "should not be more than 256 characters"}
  validates :price, :presence =>{:message => "is required"},
            :length => {:maximum => 10, :message => "should not be more than 10 digits"}
  validates :price, :numericality => true,
            :unless => Proc.new { |product| product.price.nil? }
  validates :size, :presence => {:message => "is required"},
            :length => {:maximum => 15, :message => "should not be more than 15 characters"}

  validates_attachment_presence     :photo, :message => "=> No file uploaded. Please upload the file."
  validates_attachment_size         :photo, :less_than => 5.megabytes, :message => "should be less than 5MB",
                                    :unless => Proc.new { |photo| photo.photo_file_name.blank? }
  validates_attachment_content_type :photo, 
                                    :content_type => ["image/gif","image/jpg","image/jpeg","image/png","image/pjpeg"],
                                    :message => '=> Please upload images of types jpeg, png or gif only'

  def is_new_arrival?
    new_arrival == "1"
  end

  def self.generate_code(product_id)
    "#{10000 + (product_id)}"
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  skip_before_filter :authenticate_user!, :only => [:catalogue,:detail]
  # GET /products
  # GET /products.xml
  def index

    @sub_category = SubCategory.find_by_id(params[:sub_category_id]) if params[:sub_category_id]
    @category = Category.find_by_id(@sub_category.category_id) if @sub_category
    @products = @sub_category.products

    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @sub_category = SubCategory.find_by_id(params[:sub_category_id]) if params[:sub_category_id]
    @product = Product.new(:sub_category_id => params[:sub_category_id]) if @sub_category
        
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @sub_category = SubCategory.find_by_id(params[:sub_category_id]) if params[:sub_category_id]
    @product = Product.new(params[:product].merge(:sub_category_id => params[:sub_category_id])) if @sub_category
    #To be moved to the model, the below line of code
    @product.code = Product.generate_code(@product.id) if @product and @product.save
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
#      format.html { redirect_to products_path(:sub_category_id => @product.sub_category_id) }
      format.html { redirect_to products_url(:sub_category_id => @product.sub_category_id) }
      format.xml  { head :ok }
    end
  end

  def catalogue
    @categories = Category.catalogue_details    
  end

  def detail
    @product = Product.find(params[:id])
    render :partial => 'detail'
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def formatted_products products
    formatted = []
    b = []
    while !products.empty?
      b = products.take(4)
      products = products - b
      size = b.size
      (4 - size).times {b << "1"} if size < 4
      formatted << b
    end
    formatted
  end

  def formatted_name name
     name.titleize
  end

   def formatted_description text
     text.capitalize
  end
  
end

app/views/products/_detail.html.erb
<script>
        document.createElement('header');
        document.createElement('nav');
        document.createElement('section');
        document.createElement('article');
        document.createElement('aside');
        document.createElement('footer');
        document.createElement('hgroup');
</script>
<div id="product_wrapper">
  <section class="bag">
    <%= image_tag @product.photo.url, :width => '330', :height => '440',:title => "#{@product.name.capitalize}" %>
  </section>
  <section class='bag_details'>
    <H2 class='subhead2'><%= formatted_name @product.name %><% if @product.is_new_arrival? %>&nbsp;<%= image_tag 'new_tag.jpg' %><% end %></H2>
    <table>
      <tr class='alt_row'>
        <td>Code :</td>
        <td> <%= @product.code %></td>
      </tr>
      <tr>
        <td>Price</td>
        <td>Rs.&nbsp;<%= @product.price.to_i %>/-</td>
      </tr>
      <tr class='alt_row'>
        <td>Size:</td>
        <td><%= @product.size %>&nbsp;"</td>
      </tr>

    </table>
    <table>
      <tr>
        <td>
          <b><%=  formatted_description(@product.description) %></b>
        </td>
      </tr>
    </table>
    <p class="btn_buy"><%= link_to "Interested in buying", new_enquiry_url(:product_id => @product.id),:style => 'text-decoration: none' %></p>

  </section>
  <div class='clear'></div>
  <footer class="bag_footer"><a href='mailto:wow.maitree@tcs.com'>Copyright@wow-tcs-maitree.org</a>. All Rights Reserved</footer>

</div>

app/views/products/_form.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <link rel="stylesheet" href="../stylesheets/admin_style.css"/>
    <%= javascript_include_tag "jquery.validate.min.js", "admin_custom.js" %>
  </head>
  <body>
    <div class="wrapper container_24">
      <div class="logout_layout"><%= render :partial => 'shared/logout' %></div>
      <header class="banner">
        <span>An initiative of <a id="tcs_link" href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the women of waze.</span>
      </header>
      <section class="admincontent">
        <div class="admin-banner">
          Welcome Admin
        </div>
        <div class="admin-center">
          <div class="admin-option">
            <%= form_for(@product, :html => { :id => "submit_form" }) do |f| %>
              <% if @product.errors.any? %>
                <div id="error_explanation" class ="field_with_errors">
                  <h2><%= pluralize(@product.errors.count, "error") %> prohibited this category from being saved:</h2>
                  <ul>
                    <% @product.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
            <table>
              <tr>
                <td><%= f.label :name %></td>
                <td><%= f.text_field :name %></td>
              </tr>

              <tr>
                <td><%= f.label :description %></td>
                <td><%= f.text_area :description %></td>
              </tr>
              <tr>
                <td><%= f.label :price,"Price(in INR)" %></td>
                <td><%= f.text_field :price %></td>
              </tr>
              <tr>
                <td><%= f.label :size,"Size(for e.g, 5x4x3)" %></td>
                <td><%= f.text_field :size %></td>
              </tr>
              <tr>
                <td> </td>
                <td><%= f.check_box :new_arrival %>&nbsp;<%= f.label :new_arrival %></td>
              </tr>
              <tr>
                <% if @product.errors.any? %>
                <td class="field_with_errors"><%= f.label :photo %></td>
                <%else%>
                <td><%= f.label :photo %></td>
                <%end%>
                <td><%= f.file_field :photo %></td>
              </tr>
              <% if @sub_category %>
              <%= hidden_field_tag :sub_category_id, @sub_category.id %>
              <%end%>
              <tr>
                <td><%= link_to 'Back', products_path(:sub_category_id => @product.sub_category_id) %></td>
                <td><%= f.submit %></td>
              </tr>
              </table>
            <% end %>
          </div>
        </div>
      </section>
    </div>
  </body>
</html>

app/views/products/catalogue.html.erb
<%= stylesheet_link_tag 'style-catalogue.css' %>
<script>
        document.createElement('header');
        document.createElement('nav');
        document.createElement('section');
        document.createElement('article');
        document.createElement('aside');
        document.createElement('footer');
        document.createElement('hgroup');
</script>
<div class="wrapper container_24">
  <header class="banner_sm">
    <span>An initiative of <a href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the Women of Waze.</span>
  </header>

  

  <nav class="nav2">
    <div class="internalnav_sm btn_who">
		<%= link_to 'Who we are', aboutus_url, :class=>"btn_inner_common btn_who_inner"  %>
	</div>
    <div class="internalnav_sm btn_prod">
		<%= link_to 'Shop for Our Products', catalogue_products_url, :class=>"btn_inner_common btn_prod_inner active_sel"  %>
	</div>
    <div class="internalnav_sm btn_contact">
		<%= link_to 'Get in touch', new_enquiry_url, :class=>"btn_inner_common btn_contact_inner"  %>
	</div>
  </nav>


  <section class="prod_page">

    <% flash.each do |key, value| %>
      <div class="flash_message <%= key %>"><%= value %></div>
    <% end %>


    <aside class="sidebar">
      <ul>
        <% for category in @categories %>
          <li class="cat"><%= formatted_name(category.name) %>
            <% for sub_category in category.sub_categories %>
            <li class="subcat"><%= link_to formatted_name(sub_category.name), "##{sub_category.id}" ,:style => 'text-decoration: none'%></li>
          <% end %>
          </li>
        <% end %>
      </ul>
    </aside>



    <article class="prod_grid">
      <section id="breadcrumb"><%= link_to 'Home' ,root_url %>&gt; Shop for Our Products</section>
      <table class="prod_table" id="top">
        <% for category in @categories %>
          <% for sub_category in category.sub_categories %>
            <tr class="ptitle_row">
              <td colspan="4">
                <p class="category"><%= formatted_name(category.name) %>:<%= link_to formatted_name(sub_category.name)," ",:name => "#{sub_category.id}",:class=>"subcategory",:style => 'text-decoration: none'%></p>
              </td>
            </tr>

            <% for product_list in formatted_products(sub_category.products) %>
              <tr class="prod_row">
                <% for product in product_list %>
                  <td class="prod_cell">
                    <% if product.kind_of?(Product) %>
                      <%= link_to (image_tag product.photo.url,:width =>"116" ,:height => "155",:class => "product_dialogue" , :id => "#{product.id}",:title => formatted_name(product.name)),"##{product.code}"%>
                      <p class="prod_title"><%= link_to formatted_name(product.name), "##{product.code}", :id => "#{product.id}", :class => "product_dialogue" %><% if product.is_new_arrival? %>&nbsp;<%= image_tag 'new_tag.jpg' %><% end %></p>
                      <p class="prod_text">Code: <%= product.code %><br/> Price: Rs.&nbsp;<%= product.price.to_i %>/-<br/> Size:&nbsp;<%= product.size %>&nbsp;"</p>
                      <p class="btn_buy"><%= link_to "Interested in buying", new_enquiry_url(:product_id => product.id),:style => 'text-decoration: none' %></p>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            <%end%>
            <tr class="ptitle_row">
              <td colspan="4"><p class="toplink"><a href="#">Top</a> </br>

                <hr class="prod_hr">
                </p>
              </td>
            </tr>
          <%end%>
        <%end%>
      </table>

    </article>

  </section>
</div>
<div id="product_wrapper" title = "Product Details">

</div>

<script type="text/javascript">
  $(document).ready(function(){
  $("#product_wrapper").dialog({
  autoOpen: false,
  left:2,
  top:10,
  height:580,
  width:720,
  resizable: false,
  modal: true
  // close : closeProductDialog,
  //open : openProductDialog
  });

  $(".product_dialogue").click(function(){
  var detail_url = '<%= detail_product_url(0) %>';
  $("#product_wrapper").dialog("open");
  $("#product_wrapper").html('Loading...');

  $.ajax({
  url : detail_url.replace('/0', '/' + $(this).attr('id')) ,
  dataType: 'html',
  success : function(data)
  {

  $("#product_wrapper").html(data);




  }
  });

  });

  });


</script>

app/views/products/edit.html.erb
<%= render 'form' %>
<%= javascript_tag "displayAction('Edit Product')" %>

app/views/products/index.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
  <link rel="stylesheet" href="../stylesheets/admin_style.css"/>
   <%= javascript_include_tag "jquery.validate.min.js", "admin_custom.js" %>
  </head>
  <body>
    <div class="wrapper container_24">
      <div class="logout_layout"><%= render :partial => 'shared/logout' %></div>
      <header class="banner">
       <span>An initiative of <a id="tcs_link" href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the women of waze.</span>
      </header>
      
      <section class="admincontent">
        <div class="admin-banner">
          Welcome Admin
        </div>
        <div class="admin-page-header">Products for '<%=@sub_category.name.capitalize%>' Sub-Category</div><br/><br/>
        <div class="admin-option">
          <%= link_to 'Add New Product',new_product_path(:category_id => @category.id ,:sub_category_id => @sub_category.id)%>&nbsp;&nbsp;&nbsp;
          <%= link_to 'Back to Sub-Categories', sub_categories_path(:category_id => @category.id ,:sub_category_id => @sub_category.id) %>&nbsp;&nbsp;
          <%= link_to 'Back to admin home', admin_path %>
        </div>
        <div class="categories-table">
          <table>
            <thead>
              <tr>
                <% if @products.empty?  %>
              <b>No Product for '<%=@sub_category.name.capitalize%>' Sub-Category</b>
            <%else%>
              <th>Product Photo</th><th>Code</th><th>Name</th><th>Description</th><th>Size</th><th>Show</th><th>Edit</th><th>Delete</th>
            <%end%>
            </tr>
            </thead>
            <tbody>
              <% @products.each do |product| %>
                <tr>
                  <td class="p-category"><%= link_to((image_tag product.photo.url, :height => 150, :width => 115),product) %></td>
                  <td><%= product.code %></td>
                  <td><%= product.name %></td>
                  <td><%= product.description %></td>
                  <td><%= product.size %></td>
                  <td><%= link_to 'Show', product %></td>
                  <td><%= link_to 'Edit', edit_product_path(product) %></td>
                  <td><%= link_to 'Delete', product, :confirm => 'Are you sure?', :method => :delete %></td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </body>
</html>

app/views/products/new.html.erb
<%= render 'form' %>
<%= javascript_tag "displayAction('Add New Product')" %>

app/views/products/show.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
   <link rel="stylesheet" href="../stylesheets/admin_style.css"/>
  </head>
  <body>
    <div class="wrapper container_24">
      <div class="logout_layout"><%= render :partial => 'shared/logout' %></div>
      <header class="banner">
        <span>An initiative of <a id="tcs_link" href="http://www.tcs.com/homepage/Pages/default.aspx" target="blank">TCS</a> Maitree to empower the women of waze.</span>
      </header>
       <section class="bodycontent">
        <div class="admin-banner">
          Welcome Admin
        </div>
        <div class="admin-page-header">Product of '<%=@product.sub_category.name.capitalize%>' Sub-Category</div>
        <div class="center">
          <div class="show-table">
            <table>
              <p id="notice"><%= notice %></p>
              <tr>
                <th> </th><td> <%= image_tag @product.photo.url, :height => 150, :width => 115 %></td>
              </tr>
              <tr>
                <th>Code</th> <td><%= @product.code %></td>
              </tr>
              <tr>
                <th>Name</th> <td><%= @product.name %></td>
              </tr>
              <tr>
                <th>Description</th> <td> <%= @product.description %></td>
              </tr>
              <tr>
                <th>Price</th> <td> <%= @product.price %></td>
              </tr>
              <tr>
                <th>Size:</th> <td><%= @product.size %></td>
              </tr>
              <tr>
                <td><%= link_to 'Edit', edit_product_path(@product) %></td>
                <td><%= link_to 'Back', products_path(:sub_category_id => @product.sub_category_id ) %></td>
              </tr>
            </table>
          </div>
        </div>
      </section>
    </div>
  </body>
</html>